### ISSUE TITLE
codec_time_base can be 1/0 which causes Gson deserialization to error when decoding as a Fraction.

### ISSUE THREAD

**Issue by dbousamra** [bramp/ffmpeg-cli-wrapper#10]
I receive this error:

```
Exception in thread "main" java.lang.ArithmeticException: The denominator must not be zero
	at org.apache.commons.lang3.math.Fraction.getFraction(Fraction.java:143)
	at org.apache.commons.lang3.math.Fraction.getFraction(Fraction.java:348)
	at net.bramp.commons.lang3.math.gson.FractionAdapter.read(FractionAdapter.java:37)
	at net.bramp.commons.lang3.math.gson.FractionAdapter.read(FractionAdapter.java:17)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at net.bramp.ffmpeg.FFprobe.probe(FFprobe.java:101)
```

When I try to probe an mpegts file. For reference, here is the FFProbe output as JSON:

```json
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/26",
            "codec_tag_string": "[27][0][0][0]",
            "codec_tag": "0x001b",
            "width": 1920,
            "height": 1080,
            "coded_width": 1920,
            "coded_height": 1088,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 41,
            "color_range": "tv",
            "color_space": "bt709",
            "color_transfer": "bt709",
            "color_primaries": "bt709",
            "chroma_location": "left",
            "refs": 1,
            "is_avc": "0",
            "nal_length_size": "0",
            "id": "0x100",
            "r_frame_rate": "167/12",
            "avg_frame_rate": "13/1",
            "time_base": "1/90000",
            "start_pts": 5477657,
            "start_time": "60.862856",
            "duration_ts": 378588,
            "duration": "4.206533",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            }
        },
        {
            "index": 1,
            "codec_name": "aac",
            "codec_long_name": "AAC (Advanced Audio Coding)",
            "codec_type": "audio",
            "codec_time_base": "1/0",
            "codec_tag_string": "[15][0][0][0]",
            "codec_tag": "0x000f",
            "sample_fmt": "fltp",
            "sample_rate": "0",
            "channels": 0,
            "bits_per_sample": 0,
            "id": "0x101",
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 5477657,
            "start_time": "60.862856",
            "duration_ts": 378588,
            "duration": "4.206533",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0
            }
        }
    ],
    "format": {
        "filename": "1.ts",
        "nb_streams": 2,
        "nb_programs": 1,
        "format_name": "mpegts",
        "format_long_name": "MPEG-TS (MPEG-2 Transport Stream)",
        "start_time": "60.862856",
        "duration": "4.206533",
        "size": "574528",
        "bit_rate": "1092639",
        "probe_score": 100
    }
}

```

Notice the codec_time_base is 1/0?

**Comment by bramp** [comment]
Do you know what it means to have a "1/0" timebase?

**Comment by dbousamra** [comment]
Absolutely no idea :P But, given ffprobe can emit it, I guess we need a
more flexible type then Fraction. Thoughts on just returning a String?

**Comment by bramp** [comment]
I suspect this is a quirk of ffprobe, when the time base is zero, as the
docs say the number is always 1/n when n is the time base.

I think parsing 1/0 as 0 would make the most sense, but I want to dig into
the ffprobe source first to confirm my suspicion.

**Comment by bramp** [comment]
Looked at the ffmpeg source, and codec_time_base is always 1/N (https://github.com/FFmpeg/FFmpeg/blob/v0.6.1/libavcodec/avcodec.h#L1099), so when the file contains invalid input, then N is zero, and it is printed as "1/0".

I'm going to allow the parsing to assume this means zero.
