### ISSUE TITLE
ffprobe returned non-zero exit status. Check stdout.

### ISSUE THREAD

**Issue by mohsalsaleem** [bramp/ffmpeg-cli-wrapper#129]
java.io.IOException: ffprobe returned non-zero exit status. Check stdout.
        at net.bramp.ffmpeg.FFcommon.throwOnError(FFcommon.java:59)
        at net.bramp.ffmpeg.FFprobe.probe(FFprobe.java:113)
        at net.bramp.ffmpeg.FFprobe.probe(FFprobe.java:49)

Is there any way I can see why I'm getting this exception? This is the command I'm trying to execute.
FFmpegProbeResult probeResult = this.fFprobe.probe("input.mp4");

**Comment by Omar-Riaz** [comment]
You should be able to view the error that was returned from the FFmpeg process through stdout; that is, from the source with which you are viewing this stackTrace. If it's not accessible for some reason, maybe try Overriding the `public void run(List<String> args) throws IOException` method when instantiating FFprobe to contain the message in a different way? Take a look in the FFcommon class to get the run method to override.
I guess it would be important knowing why you can't check stdout messages.

**Comment by Herz3h** [comment]
Hello,

I use this library on android with a compiled FFmpeg for android binary. And whenever i get this "returned non-zero message. Check stdout", i dont see anything in logcat, how do i get ffmpeg output message ?

**Comment by ZctrapCoding** [comment]
bump. im getting the same error. 
```
Caused by: java.lang.RuntimeException: java.io.IOException: C:/ffmpeg/bin/ffmpeg.exe returned non-zero exit status. Check stdout.
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:46)
	at commands.Commands.webMtoGif(Commands.java:90)
	at commands.Commands.gifInputStream(Commands.java:67)
	at commands.Commands.onGifCommand(Commands.java:129)
	... 11 common frames omitted
Caused by: java.io.IOException: C:/ffmpeg/bin/ffmpeg.exe returned non-zero exit status. Check stdout.
	at net.bramp.ffmpeg.FFcommon.throwOnError(FFcommon.java:51)
	at net.bramp.ffmpeg.FFcommon.run(FFcommon.java:113)
	at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:184)
	at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:202)
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:39)
	... 14 common frames omitted
```
