### ISSUE TITLE
通过Kill命令杀掉ffmpeg进程时，主进程控制台报错

### ISSUE THREAD

**Issue by bosen365** [bramp/ffmpeg-cli-wrapper#134]
在java主进程里新启一个线程来启动ffmpeg这个进程，然后我在Linux 控制台杀掉这个ffmpeg进程时，java主进程报一个异常。请问这是为何？

**Comment by bramp** [comment]
I'm sorry I can only help in English

**Comment by bosen365** [comment]
I'm sorry, I describe it in English.
When I use ffmpeg-cli-wrapper API in the main process，It create a subprocess in a new thread。when I use Java API [Runtime.getRuntime().exec()] kill the subprocess, It throw out the follow Exception.(My JDK version is 1.7.  guava is setted to 20.0.  )

Exception:IOException(path + " returned non-zero exit status. Check stdout.");

Exception in thread "pool-4-thread-1" java.lang.RuntimeException: java.io.IOException: /Users/bosen365/Documents/develop/workspace/yinktech_online/exec/ffmpeg/ffmpeg returned non-zero exit status. Check stdout.
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:43)
	at com.fanyang.service.BroadcastRtmpService$1.run(BroadcastRtmpService.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: /Users/bosen365/Documents/develop/workspace/yinktech_online/exec/ffmpeg/ffmpeg returned non-zero exit status. Check stdout.
	at net.bramp.ffmpeg.FFcommon.throwOnError(FFcommon.java:59)
	at net.bramp.ffmpeg.FFcommon.run(FFcommon.java:106)
	at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:196)
	at net.bramp.ffmpeg.FFmpeg.run(FFmpeg.java:211)
	at net.bramp.ffmpeg.job.SinglePassFFmpegJob.run(SinglePassFFmpegJob.java:36)
	... 4 more

**Comment by Euklios** [comment]
@bosen365, if there is still an issue, please provide more information on how exactly you created the thread.
And please use English.
