### ISSUE TITLE
 invalid time 'N/A' when use progress listener

### ISSUE THREAD

**Issue by ndrto** [bramp/ffmpeg-cli-wrapper#302]
**Describe the bug**
java.lang.IllegalArgumentException: invalid time 'N/A' when use progress listener.

**To Reproduce**
```java
FFmpegExecutor executor = new FFmpegExecutor(ffmpeg, ffprobe);

FFmpegProbeResult in = ffprobe.probe("input.flv");

FFmpegBuilder builder = new FFmpegBuilder()
	.setInput(in) // Or filename
	.addOutput("output.mp4")
	.done();

FFmpegJob job = executor.createJob(builder, new ProgressListener() {

	// Using the FFmpegProbeResult determine the duration of the input
	final double duration_ns = in.getFormat().duration * TimeUnit.SECONDS.toNanos(1);

	@Override
	public void progress(Progress progress) {
		double percentage = progress.out_time_ns / duration_ns;

		// Print out interesting information about the progress
		System.out.println(String.format(
			"[%.0f%%] status:%s frame:%d time:%s ms fps:%.0f speed:%.2fx",
			percentage * 100,
			progress.status,
			progress.frame,
			FFmpegUtils.toTimecode(progress.out_time_ns, TimeUnit.NANOSECONDS),
			progress.fps.doubleValue(),
			progress.speed
		));
	}
});

job.run();
```

**Version (if applicable):**
 - OS: Windows 10
 - Java Version 14

**Additional context**
// Error result
Exception in thread "TcpProgressParser(tcp://127.0.0.1:63341)" java.lang.IllegalArgumentException: invalid time 'N/A'
	at net.bramp.ffmpeg.FFmpegUtils.fromTimecode(FFmpegUtils.java:83)
	at net.bramp.ffmpeg.progress.Progress.parseLine(Progress.java:164)
	at net.bramp.ffmpeg.progress.StreamProgressParser.processReader(StreamProgressParser.java:41)
	at net.bramp.ffmpeg.progress.StreamProgressParser.processStream(StreamProgressParser.java:32)
	at net.bramp.ffmpeg.progress.TcpProgressParserRunnable.run(TcpProgressParserRunnable.java:35)

**Comment by Euklios** [comment]
@ndrto What ffmpeg version are you using?

**Comment by ndrto** [comment]
![Screenshot_136](https://github.com/bramp/ffmpeg-cli-wrapper/assets/108776670/1efb267c-ab75-46d4-b506-bcf0c4a84698)

**Comment by Euklios** [comment]
Thanks!
I don't know what the exact version is, but it is at least recent.
I'll try to reproduce this tomorrow and if possible, create a pr

**Comment by Keanu2431** [comment]
following, this happens to me on some files but not others if you need more info please reach out. or give leads as to where I can look

**Comment by Euklios** [comment]
The issue is an oversight in FFmpegUtils. Most values handle 'N/A' by returning -1; however, timecodes are missing this check.
I'm checking if there are more methods where this error could happen.
There should be a PR soon.

**Comment by ndrto** [comment]
Thanks brother, you are rock.
