### ISSUE TITLE
Document FFmpeg version supported

### ISSUE THREAD

**Issue by stonio** [bramp/ffmpeg-cli-wrapper#31]
Can you add in this project homepage useful information  for newcomers to start:
* Java version supported
* FFmpeg version supported
* Operating systems supported

**Comment by mandrakey** [comment]
Maybe the Java version (which was added to the readme, I just saw a "Java 7+" sign there). As for the other two:

* Operating systems: As this is pure Java code, it will run everywhere Java and FFmpeg work. I believe there are ports of both for almost any popular system. Even Android works.
* FFmpeg versions: The FFmpeg guys always state that FFmpeg is built with a very stable interface. I have used even rather complex commands documented in the web years ago on recent versions without problems.

**Comment by CaMauHap** [comment]
Hi I install ffmpeg for window follow this [instruction ](http://www.wikihow.com/Install-FFmpeg-on-Windows) , and I try to run test as your guide
`FFmpeg ffmpeg = new FFmpeg("/path/to/ffmpeg");`
`FFprobe ffprobe = new FFprobe("/path/to/ffprobe");
`
My code is 
`try {
			FFmpeg ffmpeg = new FFmpeg("C:/ffmpeg");
			FFprobe ffprobe = new FFprobe("C:/ffprobe");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}`

The error is 

> [main] INFO net.bramp.ffmpeg.RunProcessFunction - C:/ffmpeg -version
java.io.IOException: Cannot run program "C:/ffmpeg": CreateProcess error=5, Access is denied
	at java.lang.ProcessBuilder.start(Unknown Source)
	at net.bramp.ffmpeg.RunProcessFunction.run(RunProcessFunction.java:38)
	at net.bramp.ffmpeg.FFcommon.version(FFcommon.java:66)
	at net.bramp.ffmpeg.FFmpeg.version(FFmpeg.java:1)
	at net.bramp.ffmpeg.FFmpeg.<init>(FFmpeg.java:89)
	at net.bramp.ffmpeg.FFmpeg.<init>(FFmpeg.java:84)
	at com.ytb.Render.main(Render.java:13)
Caused by: java.io.IOException: CreateProcess error=5, Access is denied
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 7 more

Please help me to overcome it.

**Comment by bramp** [comment]
I doubt the ffmpeg is at 'C:/ffmpeg'

From the tutorial it looks like it is at 'c:\ffmpeg\bin\ffmpeg.exe'. However if you followed instruction #3 you should be able to just say 'ffmpeg' and it will find it on your path.

**Comment by CaMauHap** [comment]
Ah ha, I got it. Btw, i want to draw  text on video screen like [this ](http://stackoverflow.com/questions/17623676/text-on-video-ffmpeg) , Can you show me which class I can use ? 
Thanks,
