### ISSUE TITLE
FFmpegUtils.parseBitrate throws IllegalArgument when bitrate is 'N/A'

### ISSUE THREAD

**Issue by mspandriesse** [bramp/ffmpeg-cli-wrapper#86]
When using a ProgressListener, the first message contains "N/A" for the bitrate. This causes the TcpProgressParserRunnable to exit:
```
Exception in thread "TcpProgressParser(tcp://127.0.0.1:58092)" java.lang.IllegalArgumentException: Invalid bitrate 'N/A'
	at net.bramp.ffmpeg.FFmpegUtils.parseBitrate(FFmpegUtils.java:64)
	at net.bramp.ffmpeg.progress.Progress.parseLine(Progress.java:76)
	at net.bramp.ffmpeg.progress.StreamProgressParser.processReader(StreamProgressParser.java:41)
	at net.bramp.ffmpeg.progress.StreamProgressParser.processStream(StreamProgressParser.java:32)
	at net.bramp.ffmpeg.progress.TcpProgressParserRunnable.run(TcpProgressParserRunnable.java:35)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mspandriesse** [comment]
Ok. I see now, it is on the ToDo list.

**Comment by bramp** [comment]
I welcome patches to fix this. Perhaps returning -1 if the bitrate is N/A

**Comment by zipper2110** [comment]
Proposed pull request to fix this: https://github.com/bramp/ffmpeg-cli-wrapper/pull/92
